In [1]:
import torch.nn as nn
import torch
import torch.nn.functional as F

In [5]:
class MLP(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        super(MLP, self).__init__()
        # 定义第一个 线性层
        self.fc1 = nn.Linear(input_dim, hidden_dim)
        # 定义第二个 线性层
        self.fc2 = nn.Linear(hidden_dim, output_dim)
    def forward(self, x_in, apply_softmax = False):
        # 前向传播， 调用第一个线性层，最后采用 relu函数
        # 即 inter_data1 = relu（A）, A = W1 * x_in + b1
        # 这里需要用一个 非线性运算，因为不用的话，两层 线性运算其实就是一层了
        # x_in 的维度 应该是（batch, inpt_dim）
        inter_data1 = F.relu(self.fc1(x_in))
        # 调用第二个线性层，output = W2 * inter_data1 + b2
        output = self.fc2(inter_data1)

        if apply_softmax:
            output = F.softmax(output, dim = 1)
        return output

In [7]:
batch_size = 2
input_dim = 3
hidden_dim = 100
output_dim = 4
mlp = MLP(input_dim, hidden_dim, output_dim)
print(mlp)

MLP(
  (fc1): Linear(in_features=3, out_features=100, bias=True)
  (fc2): Linear(in_features=100, out_features=4, bias=True)
)


In [9]:
def des(x):
    print("Type: {}".format(x.type()))
    print("Shape/size: {}".format(x.shape))
    print("Values: \n{}".format(x))
x_input = torch.rand(batch_size, input_dim)
des(x_input)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.1836, 0.8085, 0.7750],
        [0.3319, 0.4995, 0.5524]])


In [13]:
y_output = mlp.forward(x_input)
des(y_output)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 4])
Values: 
tensor([[-0.2029,  0.0972,  0.1814,  0.2489],
        [-0.1796,  0.0884,  0.2177,  0.2243]], grad_fn=<AddmmBackward>)


In [15]:
y_output = mlp.forward(x_input, apply_softmax = True)
des(y_output)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 4])
Values: 
tensor([[0.1855, 0.2505, 0.2725, 0.2915],
        [0.1889, 0.2470, 0.2811, 0.2830]], grad_fn=<SoftmaxBackward>)


In [19]:
# 生成维度 为列 dim=1嘛
print(torch.sum(y_output, dim = 1))

tensor([1.0000, 1.0000], grad_fn=<SumBackward1>)
